"use client";

import "./globals.css";
import { Inter, Lato, Roboto } from "next/font/google";
import { SessionProvider } from "next-auth/react";
const inter = Lato({ subsets: ["latin"], weight: ["400"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, session }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider session={session}>{children}</SessionProvider>
      </body>
    </html>
  );
}
